# Generated by Django 4.2.2 on 2023-06-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user_alter_article_writer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
